### ISSUE TITLE
Question: Are you planning on expanding beyond lights to sockets and other LightwaveRF devices?

### ISSUE THREAD

**Issue by RevillWeb** [SCCMOG/Home-Assistant#1]
Hi,

First of all, thank you! I've been waiting for a LightwaveRF integration for Home Assistant for a while, I'm looking forward to trying this out.

Are you planning on expanding beyond lights to sockets and other LightwaveRF devices?

Thanks!

**Comment by SCCMOG** [comment]
Hi buddy,

No worries glad someone is using it :)
To be honest the only reason I did it was because every light switch in my house is a LightwaveRF dimmer. I don’t have any power sockets at the mo or other devices as I went for z wave in the end. But hey why not I’ll order one and let you know when I’ve done it :)

Cheers,

Richie

**Comment by aracdin** [comment]
I hacked Richie's code to handle sockets - but as I'm only using sockets I didn't have to support both. As soon as I understand how the whole thing works I'll create a socket component that can work along side lights. Richie points out it's a simple copy/paste/rename but I would like to understand what I'm doing first :-)
